### PR TITLE
added visible data api

### PR DESCRIPTION
**Pull request by mawsyh**
exposed the API to get data of the visible part of the chart

### CODE REVIEW

**Comment by liihuu** [comment]
`getVisibleRange()`?

**Comment by mawsyh** [comment]
Correct if I'm wrong but visibleRange returns a single object with from and to values, but i needed the array of visible data to do some mathematical calculations on them

**Comment by liihuu** [comment]
From and to are KLineData array index, only need to get the current data through `getDataList`.

**Comment by liihuu** [comment]
From and to are KLineData array index, only need to get the current data through `getDataList`.

**Comment by mawsyh** [comment]
Thanks but in some cases I have over 10000 objects in my data, fetching them all and slicing it doesn't seem the best approach to me.

**Pull request closed without merging**
